---
# Title: role-ansible-server 
#
# Author: Luc Rutten
# File: tasks/main.yml
#
# Description:
#   Ansible default deployment server

- name: "Install packages"
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - apache2

- name: "Create directory structure"
  file:
    path: "{{ item }}"
    state: directory
    owner: ansible
    group: ansible
    mode: 0755
  with_items:
    - /opt/resource
    - /opt/backup

- name: "Create symlink to www"
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    owner: root
    group: root
    mode: 0755
  with_items:
    - { src: '/opt/resource', dest: '/var/www/html/resource' }
    - { src: '/opt/backup', dest: '/var/www/html/backup' }

- name: "Transfer templates"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'apache2/index.html.j2', dest: '/var/www/html/index.html',
        owner: 'root', group: 'root', mode: '0644' }
    - { src: 'apache2/security.conf.j2', dest: '/etc/apache2/conf-available/security.conf',
        owner: 'root', group: 'root', mode: '0644' }
  notify:
    - apache2_restart

- name: "UFW Allow traffic on port 80/tcp"
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items:
    - { rule: 'allow', port: '80', proto: 'tcp' }
